// <auto-generated />
using System;
using FrogBets.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FrogBets.Infrastructure.Migrations
{
    [DbContext(typeof(FrogBetsDbContext))]
    [Migration("20260408231414_MakeCS2PlayerTeamIdNullable")]
    partial class MakeCS2PlayerTeamIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrogBets.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ActorId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CoveredById")
                        .HasColumnType("uuid");

                    b.Property<string>("CovererOption")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorOption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Result")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoveredById");

                    b.HasIndex("CreatorId");

                    b.HasIndex("MarketId");

                    b.HasIndex("Status");

                    b.HasIndex("MarketId", "CreatorId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.CS2Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<double>("PlayerScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("RealName")
                        .HasColumnType("text");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("CS2Players");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.CS2Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CS2Teams");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfMaps")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TeamA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TeamB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.GameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MapNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegisteredByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("WinningOption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MarketId")
                        .IsUnique();

                    b.HasIndex("RegisteredByAdminId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UsedByUserId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.MapResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("MapNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Rounds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "MapNumber")
                        .IsUnique();

                    b.ToTable("MapResults");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MapNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WinningOption")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId", "Type", "MapNumber")
                        .IsUnique();

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.MatchStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<double>("KastPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<Guid>("MapResultId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalDamage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MapResultId");

                    b.HasIndex("PlayerId", "MapResultId")
                        .IsUnique();

                    b.ToTable("MatchStats");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.RevokedToken", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.TradeListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TradeListings");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.TradeOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OfferedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProposerTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OfferedUserId");

                    b.HasIndex("ProposerTeamId");

                    b.HasIndex("ReceiverTeamId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("TradeOffers");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeamLeader")
                        .HasColumnType("boolean");

                    b.Property<int>("LossesCount")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ReservedBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("VirtualBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WinsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Bet", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.User", "CoveredBy")
                        .WithMany("CoveredBets")
                        .HasForeignKey("CoveredById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrogBets.Domain.Entities.User", "Creator")
                        .WithMany("CreatedBets")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.Market", "Market")
                        .WithMany("Bets")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoveredBy");

                    b.Navigation("Creator");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.CS2Player", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.CS2Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrogBets.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("FrogBets.Domain.Entities.CS2Player", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.GameResult", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.Market", "Market")
                        .WithMany("GameResults")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.User", "RegisteredByAdmin")
                        .WithMany()
                        .HasForeignKey("RegisteredByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Market");

                    b.Navigation("RegisteredByAdmin");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Invite", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.User", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.MapResult", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Market", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.Game", "Game")
                        .WithMany("Markets")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.MatchStats", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.MapResult", "MapResult")
                        .WithMany("Stats")
                        .HasForeignKey("MapResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.CS2Player", "Player")
                        .WithMany("Stats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MapResult");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.TradeListing", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.CS2Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.TradeOffer", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.User", "OfferedUser")
                        .WithMany()
                        .HasForeignKey("OfferedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.CS2Team", "ProposerTeam")
                        .WithMany()
                        .HasForeignKey("ProposerTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.CS2Team", "ReceiverTeam")
                        .WithMany()
                        .HasForeignKey("ReceiverTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfferedUser");

                    b.Navigation("ProposerTeam");

                    b.Navigation("ReceiverTeam");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.User", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.CS2Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.CS2Player", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.CS2Team", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Game", b =>
                {
                    b.Navigation("Markets");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.MapResult", b =>
                {
                    b.Navigation("Stats");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Market", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("GameResults");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.User", b =>
                {
                    b.Navigation("CoveredBets");

                    b.Navigation("CreatedBets");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
