// <auto-generated />
using System;
using FrogBets.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FrogBets.Infrastructure.Migrations
{
    [DbContext(typeof(FrogBetsDbContext))]
    [Migration("20260406160939_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrogBets.Domain.Entities.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CoveredById")
                        .HasColumnType("uuid");

                    b.Property<string>("CovererOption")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorOption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Result")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoveredById");

                    b.HasIndex("CreatorId");

                    b.HasIndex("MarketId");

                    b.HasIndex("Status");

                    b.HasIndex("MarketId", "CreatorId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfMaps")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TeamA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TeamB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.GameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MapNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RegisteredByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("WinningOption")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("MarketId")
                        .IsUnique();

                    b.HasIndex("RegisteredByAdminId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MapNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WinningOption")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameId", "Type", "MapNumber")
                        .IsUnique();

                    b.ToTable("Markets");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<int>("LossesCount")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ReservedBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("VirtualBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WinsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Bet", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.User", "CoveredBy")
                        .WithMany("CoveredBets")
                        .HasForeignKey("CoveredById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FrogBets.Domain.Entities.User", "Creator")
                        .WithMany("CreatedBets")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.Market", "Market")
                        .WithMany("Bets")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoveredBy");

                    b.Navigation("Creator");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.GameResult", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.Market", "Market")
                        .WithMany("GameResults")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FrogBets.Domain.Entities.User", "RegisteredByAdmin")
                        .WithMany()
                        .HasForeignKey("RegisteredByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Market");

                    b.Navigation("RegisteredByAdmin");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Market", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.Game", "Game")
                        .WithMany("Markets")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Notification", b =>
                {
                    b.HasOne("FrogBets.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Game", b =>
                {
                    b.Navigation("Markets");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.Market", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("GameResults");
                });

            modelBuilder.Entity("FrogBets.Domain.Entities.User", b =>
                {
                    b.Navigation("CoveredBets");

                    b.Navigation("CreatedBets");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
